### ISSUE TITLE
The retrieval-based method

### ISSUE THREAD

**Issue by Sjzwind** [facebookresearch/EmpatheticDialogues#12]
Hi, I have several questions regarding retrieval-based model

    1. How do you get 100 candidates at inference time in calculating P@1, 100
    2. At training time, you use all of the utterances from the batch as candidates to minimize the negative log-likelihood of selecting the correct candidate. Why not sample negative examples of a certain proportion. For example, sample 9 negative examples for one positive example. Did you compare these two methods?

Looking forward to your reply.
Best wishes

**Comment by EricMichaelSmith** [comment]
Hi there!
1. We split the candidates into groups of 100 at https://github.com/facebookresearch/EmpatheticDialogues/blob/master/retrieval_train.py#L137 .
2. Do you mean using 9 negative examples instead of 511 negative examples for a batch size of 512? Generally I've found that larger candidate batches work better for training retrieval models. One intuition for this is that it's a harder job to select the right answer among 100 candidates vs. 10 candidates, and so the model learns more information about how to pick the right candidate if it has to pick among a larger pool.

**Comment by Sjzwind** [comment]
> Hi there!
> 
> 1. We split the candidates into groups of 100 at https://github.com/facebookresearch/EmpatheticDialogues/blob/master/retrieval_train.py#L137
> 2. Do you mean using 9 negative examples instead of 511 negative examples for a batch size of 512? Generally I've found that larger candidate batches work better for training retrieval models. One intuition for this is that it's a harder job to select the right answer among 100 candidates vs. 10 candidates, and so the model learns more information about how to pick the right candidate if it has to pick among a larger pool.

I mean that If I get 1 positive instance and 9 negative instances. It's a two-classifier task, I just need to which one is more likely to be a positive instance in one postive and one negative instance. It's pointwise-type, your method is like pairwise-type, but pairwise-type learning contains context, one positive and one negative instance, your method contains context, one positive and {batch_size - 1} negative instances. I don't know you test the two methods.

**Comment by EricMichaelSmith** [comment]
Oh, I think I see what you're saying - yes, we're using a biencoder architecture, which considers the [batch, batch] dot-products matrix of contexts and responses. No, we haven't tried a cross-encoder architecture, which would concatenate the contexts and responses together. I imagine that that architecture would likely perform a bit better, at the expense of slower training speed.

**Comment by Sjzwind** [comment]
Thank you for your reply : )

**Comment by EricMichaelSmith** [comment]
No problem!
